export const APP_NAME = 'ForgeX'
export const APP_ID = 'com.forgex.app'

export const IGNORED_DIRS = new Set([
  'node_modules',
  '.git',
  'dist',
  'build',
  'out',
  '.next',
  '.nuxt',
  '.output',
  'coverage',
  '.cache',
  '.turbo',
  '.vite',
  '__pycache__',
  '.venv',
  'venv',
  '.idea',
  '.DS_Store'
])

export const IGNORED_FILES = new Set(['.DS_Store', 'Thumbs.db', 'desktop.ini'])

export const MAX_FILE_SIZE_BYTES = 2 * 1024 * 1024 // 2MB
export const MAX_FILE_PREVIEW_CHARS = 500_000
export const MAX_DIFF_SIZE_BYTES = 1 * 1024 * 1024

export const DEFAULT_SETTINGS = {
  grokBuildPath: '',
  defaultShell: '',
  defaultProjectDir: '',
  theme: 'light' as const,
  fontSize: 13,
  terminalFontSize: 13,
  autoRestoreProject: true,
  autoRestoreSession: false,
  showVerboseLogs: false,
  editorWordWrap: true,
  editorFontSize: 13
}

export const BINARY_EXTENSIONS = new Set([
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'ico',
  'bmp',
  'svg',
  'pdf',
  'zip',
  'tar',
  'gz',
  'bz2',
  '7z',
  'rar',
  'exe',
  'dll',
  'so',
  'dylib',
  'bin',
  'wasm',
  'woff',
  'woff2',
  'ttf',
  'otf',
  'eot',
  'mp3',
  'mp4',
  'wav',
  'avi',
  'mov',
  'webm',
  'ogg',
  'flac',
  'class',
  'o',
  'a',
  'lib',
  'pdb',
  'sqlite',
  'db',
  'node'
])

export const LANGUAGE_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'typescript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  md: 'markdown',
  mdx: 'markdown',
  css: 'css',
  scss: 'scss',
  less: 'less',
  html: 'html',
  htm: 'html',
  xml: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'ini',
  py: 'python',
  rs: 'rust',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  rb: 'ruby',
  php: 'php',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ps1: 'powershell',
  sql: 'sql',
  graphql: 'graphql',
  gql: 'graphql',
  vue: 'html',
  svelte: 'html',
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  rsx: 'rust',
  env: 'ini',
  conf: 'ini',
  ini: 'ini',
  log: 'plaintext',
  txt: 'plaintext'
}
